modules:
  mytcp4:
    prober: tcp
    timeout: 25s
    tcp:
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: false
  myicmp4:
    prober: icmp
    timeout: 3s
    icmp:
      preferred_ip_protocol: "ipv4"
      ip_protocol_fallback: false
      payload_size: 128
  mydns4:
    prober: dns
    timeout: 5s
    dns:
      preferred_ip_protocol: "ipv4"
      ip_protocol_fallback: false
      transport_protocol: "udp"
      query_name: "www.cloudflare.com"
      query_type: A
